### ISSUE TITLE
Static file serving is incredibly slow

### ISSUE THREAD

**Issue by xy-kasumi** [xy-kasumi/bonsai-massive#59]

**Comment by xanxys** [comment]
Very strange TCP packets:
ab -c 1 -n 1 "http://bonsai-staging.xanxys.net/static/vue.js"


![screenshot from 2016-06-26 14 56 33](https://cloud.githubusercontent.com/assets/538821/16360767/3c4f1e48-3bae-11e6-9b10-786ebf9476d6.png)

**Comment by xanxys** [comment]
I also checked the node's persistent disk performance by time sha256 (random 1MB file) by ssh-ing, but they were super fast

**Comment by xanxys** [comment]
Maybe filesystem is not a problem, but maybe load balancer is incorrectly configured?
When a response fits in a packet, they're fast as normal, but bigger responses are triggering strange behavior?

**Comment by xanxys** [comment]
Also checked MTUs (cf. https://cloud.google.com/compute/docs/troubleshooting#communicatewithinternet)
but they (i.e. GKE node itself and container inside it) had MTU 1460.

**Comment by xanxys** [comment]
Also tested wget, sha256sum (probably provided by busybox) within the pod container, but they're fast. Another evidence PD is not a problem here.

**Comment by xanxys** [comment]
Turning down one service temporarily
`kubectl scale --replicas=0 rc/bonsai-prod-frontend-rc`
didn't help speed of `wget  --no-cache -O /dev/null http://104.154.86.8/static/vue.js`
so "load balancer ingress packet incorrectly handled by multiple different services" hypothesis is rejected.

**Comment by xanxys** [comment]
Confirmed this is not related to PD, since adding garbage text to API proto and disabling gzip resulted in same kind of slow download.

**Comment by xanxys** [comment]
similar case for AWS backed cluster https://github.com/kubernetes/kubernetes/issues/11632

**Comment by xanxys** [comment]
Have no idea, but recreating all SVCs (along with LBs) solved the issue. Maybe older version of kubernetes / GKE had problem w/ LB setup or something.
